#!/usr/bin/php
<?php
//****************************************************************
//
//		Autor		: 	BOUDI Ludovic
//		Date		:	01-11-2016
//		Description :	portage de la commande PowerShell 
//						Get-Service pour linux
//
//****************************************************************

// La commande "Get-Service" permet de recuperer la liste des
// services actif sur votre systeme. 

var $output;
var $cmd;

if ($argc == 1)
{
	$output = shell_exec ('systemctl status');
	echo $output;
}
else if ($argc == 2)
{
	$cmd = 'systemctl status ' . $argv[1];
	$output = shell_exec ($cmd);
	echo $output;
}
?>