#!/usr/bin/bash
<?php
//*******************************************************************
//
//		Autor		: BOUDI Ludovic
//		date		: 14-11-2016
//		Description	: Automatisation de l'installation de OpenEdX 
//					  Pour Ubuntu
//*******************************************************************

// IMPORTANT NOTICE :
// This script is supposed to be run with root privilege

function SeekAndReplace($Search,$Replace,$File)
{
	$content=str_replace($Search,$Replace,file_get_contents($File));
	file_put_contents($File,$content);
}

var $output;

$output=shell_exec('apt-get update -y');
echo $output;
$output=shell_exec('apt-get install -y build-essential software-properties-common python-software-properties curl git-core libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev libxmlsec1-dev swig libmysqlclient-dev');
echo $output;
$output=shell_exec('pip install --upgrade pip');
echo $output;
$output=shell_exec('pip install --upgrade virtualenv');
echo $output;
$output=shell_exec('cd /var/tmp; git clone https://github.com/edx/configuration');
echo $output;
SeekAndReplace('COMMON_SSH_PASSWORD_AUTH="no"','COMMON_SSH_PASSWORD_AUTH="yes"','/var/tmp/configuration/playbooks/roles/common_vars/defaults/main.yml');
$output=shell_exec('cd /var/tmp/configuration; pip install -r requirements.txt; pip install setuptools --upgrade');
echo $output;
$output=shell_exec('cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"');
echo $output;
?>