#!/usr/bin/bash
<?php
//*******************************************************************
//
//		Autor		: BOUDI Ludovic
//		date		: 14-11-2016
//		Description	: Jeu avec pile LIFO FIFO
//*******************************************************************

$LIFO = array();
$FIFO = array();
$LIFOcount = -1;
$FIFOcount = -1;

function AddDataToLifo($Data)
{
	global $LIFO;
	global $LIFOcount;
	$LIFOcount++;
	$LIFO[$LIFOcount] = $Data;
	
}

function ExtractDataFromLifo()
{
	global $LIFO;
	global $LIFOcount;
	if ($LIFOcount== -1)
	{
		return null;
	}
	else
	{
		$Data = $LIFO[$LIFOcount];
		$LIFOcount--;
		return $Data;
	}	
}

function AddDataToFifo($Data)
{
	global $FIFO;
	global $FIFOcount;
	$FIFOcount++;
	$FIFO[$FIFOcount] = $Data;
	
}
function ExtractDataFromFifo()
{
	global $FIFO;
	global $FIFOcount;
	if ($FIFOcount== -1)
	{
		return null;
	}
	else
	{
		$Data = $LIFO[0];
		$Loop = 0;
		foreach ($FIFO as &$element)
		{
			$loop++;
			$element = $FIFO[$Loop];
		}
		$LIFOcount--;
		return $Data;
	}	
}

?>