#!/usr/bin/bash
<?php
//*******************************************************************
//
//		Autor		: BOUDI Ludovic
//		date		: 14-11-2016
//		Description	: ajout automatique de dns dans le fichier hosts
//*******************************************************************

// IMPORTANT NOTICE :
// This script is supposed to be run with root privilege

function AddDNStoHosts($Addr, $Host)
{
	$file = fopen ("/etc/hosts", "r+");
	$Data = $Addr . "\t" . $Host . "\n";
	fputs ($file, $Data);
	fclose($file);
}

$DNS=array();
var $IP;
var $Name;
include '/etc/DnsAdd.conf';

foreach ($DNS as &$element)
{
	list($IP, $Name)= explode("|",$element);
	AddDNStoHosts($IP, $Name);
}
unset $element;
?>