#!/usr/bin/php
<?php
//**************************************************************************
//			Autor 		: BOUDI Ludovic
//			Date		: 09-11-2016
//			Description	: envoyer un mail en PHP depuis la ligne de commande
//**************************************************************************

var $Destinataire;
var $Sujet;
var $Message;
var $Emetteur;

echo "Veuillez saisir votre adresse mail :\n";
$Emetteur = trim(fgets(STDIN));
$Emetteur = "From : " . $Emetteur . "\r\n";
echo "Veuillez saisir l adresse mail de votre destinataire:\n";
$Destinataire = trim(fgets(STDIN));
echo "Veuillez saisir le sujet de votre mail :\n";
$Sujet == trim(fgets(STDIN));
echo "Veuillez saisir le message de votre mail :\n";
$Message = trim(fgets(STDIN));
// ci dessous la mise en forme du message
// car celui ci ne peut contenir plus de 
// 70 caractere sans saut de ligne
$Message = wordwrap($Message, 70, "\r\n");

// envoie du mail
mail($Destinataire, $Sujet, $Message, $Emetteur);
?>