#!/usr/bin/php
<?php
//****************************************************************
//
//		Autor		: 	BOUDI Ludovic
//		Date		:	01-11-2016
//		Description :	ajout de la commande type PowerShell 
//						Set-Service pour linux
//
//****************************************************************

// La commande "Set-Service" permet d'interagir avec les
// services de votre systeme. 

function usage()
{
	echo "Set-Service <etat> <service> \n";
	echo "Etat pouvant etre : \n";
	echo "\t - auto : activer le demarrage automatique d'un service \n";
	echo "\t - manuel : pour choisir de definir un service comme etant en activation manuelle \n";
	echo "\t - start : pour demarrer un service";
	echo "\t - stop : pour arreter un service";
	echo "\t - restart : pour redemarre un service";
}

// a savoir la gestion des services linux par system.d (commande systemctl) est 
// beaucoup plus complete que celle de windows car il y aurait en plus les options
// de load et relaod de service

$state;
$cmd;


// control saisie utilisateur
if ($argc != 2)
{
	usage();
	exit(1); 
}
if (($argv[1]!= "auto") || ($argv[1]!= "manuel") || ($argv[1]!= "start") || ($argv[1]!= "stop" )|| ($argv[1]!= "restart"))
{
	usage();
	exit(1); 
}
switch ($argv[1])
{
	case "auto" :
		$state = "enable";
		break
	case "manuel" :
		$state = "disable";
		break
	case "start" :
		$state = "start";
		break
	case "stop" :
		$state = "stop";
		break
	case "restart" :
		$state = "restart";
		break
}
$cmd = "systemctl " . $state . " " . $argv[2];
shell_exec($cmd);
?>
